name: Build and Release YTMusicUltimate
on:
  workflow_dispatch:
    inputs: 
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube Music"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtubemusic"
        required: true
        type: string

      rymd:
        description: "Integrate Return YouTubeMusic Dislikes"
        type: boolean
        required: true
        default: false

      ytmabc:
        description: "Integrate YTMABConfig"
        type: boolean
        required: true
        default: false

      youmusicpip:
        description: "Integrate YouMusicPiP"
        type: boolean
        required: true
        default: false

      volumeboostyt:
        description: "Integrate VolumeBoostYT"
        type: boolean
        required: true
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTMusicUltimate
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.3
        with:
          path: main
          submodules: recursive

      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@1.2.0
        with:
          exclude_inputs: bundle_id,display_name,rymd,ytmabc,youmusicpip,volumeboostyt

      - name: Download and Validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --quiet --no-verbose -O ytm.ipa
          file_type=$(file --mime-type -b ytm.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Get YouTube Music Version
        run: |
          unzip -q ytm.ipa -d ytmextracted
          echo "YTM_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ytmextracted/Payload/*.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
          rm -rf ytmextracted

      - name: Get Tweak Version
        run: |
          echo "YTMU_VERSION=$(grep '^PACKAGE_VERSION' main/Makefile | awk -F' = ' '{print $2}')" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          brew uninstall --ignore-dependencies bicep || true
          brew untap aws/tap azure/bicep || true
          brew install make ldid

      - name: Set PATH Environment Variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Cache Theos
        id: theos
        uses: actions/cache@v5.0.5
        env:
          cache-name: theos_cache_9bc7340_sdk18.6
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v6.0.3
        with:
          repository: theos/theos
          ref: 9bc73406cf80b711ef4d02c15ff1dedc4478a275
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Clone YouTubeHeader
        run: |
          rm -rf $THEOS/include/YouTubeHeader
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git $THEOS/include/YouTubeHeader

      - name: Clone PSHeader
        run: |
          rm -rf $THEOS/include/PSHeader
          git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git $THEOS/include/PSHeader

      - name: Clone YouTubeMusicHeader
        run: |
          rm -rf $THEOS/include/YouTubeMusicHeader
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeMusicHeader.git $THEOS/include/YouTubeMusicHeader

      - name: Clone Return YouTube Dislikes
        if: ${{ inputs.rymd }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git

      - name: Clone YouPiP
        if: ${{ inputs.youmusicpip }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouPiP.git

      - name: Clone and Build Return YouTubeMusic Dislikes
        if: ${{ inputs.rymd }}
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Music-Dislikes.git
          cd Return-YouTube-Music-Dislikes && make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/rymd.deb

      - name: Clone and Build YTMABConfig
        if: ${{ inputs.ytmabc }}
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTMABConfig.git
          cd YTMABConfig && make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytmabc.deb

      - name: Clone and Build YouMusicPiP
        if: ${{ inputs.youmusicpip }}
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouMusicPiP.git
          cd YouMusicPiP && make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youmusicpip.deb

      - name: Clone and Build VolumeBoostYT
        if: ${{ inputs.volumeboostyt }}
        run: |
          git clone --quiet --depth=1 https://github.com/VasirakCalgux/VolumeBoostYT.git
          cd VolumeBoostYT && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/volumeboostyt.deb

      - name: Build Tweak for Sideloading
        run: |
          cd main
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless SIDELOADING=1
          mv packages/*.deb ../ytmult.deb

      - name: Inject Tweak Into IPA
        run: |
          tweaks="ytmult.deb"
          for f in rymd.deb ytmabc.deb youmusicpip.deb volumeboostyt.deb; do
            [ -f "$f" ] && tweaks="$tweaks $f"
          done
          cyan -i ytm.ipa -o YTMusicUltimate_${{ env.YTM_VERSION }}_${{ env.YTMU_VERSION }}.ipa -uwesf $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ytmu-ipa${{ github.run_number }}
          name: YTMusicUltimate_${{ env.YTM_VERSION }}_${{ env.YTMU_VERSION }} (${{ github.run_number }})
          files: YTMusicUltimate_${{ env.YTM_VERSION }}_${{ env.YTMU_VERSION }}.ipa
          draft: true

      - name: Job Summary - Build Complete
        run: echo -e '### 🛠️ Build YTMusicUltimate IPA Complete!' >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output the Draft Release Link
        run: |
          echo -e "### 🚀 Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases" >> $GITHUB_STEP_SUMMARY
